const LOGIN_ERROR = 100;
const SINGNUP_ERROR = 110;
const ACCESS_DENIED = 120;
const CREATEING_ERROR = 130;
const NOT_FOUND = 140;
const ALREADY_EXISTS = 150;

export {
    LOGIN_ERROR,
    SINGNUP_ERROR,
    ACCESS_DENIED,
    CREATEING_ERROR,
    NOT_FOUND,
    ALREADY_EXISTS,
};
